version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - TimSatke
  ignore:
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: golang.org/x/text
    versions:
    - 0.3.5
