// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Error-1]
	_ = x[LineTerminator-2]
	_ = x[MultiLineComment-3]
	_ = x[SingleLineComment-4]
	_ = x[Whitespace-5]
}

const _Type_name = "UnknownErrorLineTerminatorMultiLineCommentSingleLineCommentWhitespace"

var _Type_index = [...]uint8{0, 7, 12, 26, 42, 59, 69}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
