// Code generated by "stringer -type=param"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pAwait-2]
	_ = x[pDefault-4]
	_ = x[pIn-8]
	_ = x[pReturn-16]
	_ = x[pTagged-32]
	_ = x[pYield-64]
}

const (
	_param_name_0 = "pAwait"
	_param_name_1 = "pDefault"
	_param_name_2 = "pIn"
	_param_name_3 = "pReturn"
	_param_name_4 = "pTagged"
	_param_name_5 = "pYield"
)

func (i param) String() string {
	switch {
	case i == 2:
		return _param_name_0
	case i == 4:
		return _param_name_1
	case i == 8:
		return _param_name_2
	case i == 16:
		return _param_name_3
	case i == 32:
		return _param_name_4
	case i == 64:
		return _param_name_5
	default:
		return "param(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
