// Code generated by "aststring"; DO NOT EDIT.
package ast

import (
	"bytes"
	"fmt"
)

func (node *FormalParameters) String() string {
	var buf bytes.Buffer
	buf.WriteString("FormalParameters (")
	buf.WriteString("\n")
	if node.FunctionRestParameter != nil {
		buf.WriteString(PrefixToString(node.FunctionRestParameter.String(), "  "))
	}
	if node.FormalParameterList != nil {
		buf.WriteString(PrefixToString(node.FormalParameterList.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Comma", node.Comma), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *FunctionRestParameter) String() string {
	var buf bytes.Buffer
	buf.WriteString("FunctionRestParameter (")
	buf.WriteString("\n")
	if node.BindingRestElement != nil {
		buf.WriteString(PrefixToString(node.BindingRestElement.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *FormalParameterList) String() string {
	var buf bytes.Buffer
	buf.WriteString("FormalParameterList (")
	buf.WriteString("\n")
	for _, elem := range node.FormalParameters {
		buf.WriteString(PrefixToString(elem.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *FormalParameter) String() string {
	var buf bytes.Buffer
	buf.WriteString("FormalParameter (")
	buf.WriteString("\n")
	if node.BindingElement != nil {
		buf.WriteString(PrefixToString(node.BindingElement.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *FunctionBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("FunctionBody (")
	buf.WriteString("\n")
	if node.FunctionStatementList != nil {
		buf.WriteString(PrefixToString(node.FunctionStatementList.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *FunctionStatementList) String() string {
	var buf bytes.Buffer
	buf.WriteString("FunctionStatementList (")
	buf.WriteString("\n")
	if node.StatementList != nil {
		buf.WriteString(PrefixToString(node.StatementList.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *GeneratorBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("GeneratorBody (")
	buf.WriteString("\n")
	if node.FunctionBody != nil {
		buf.WriteString(PrefixToString(node.FunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *ArrowFunction) String() string {
	var buf bytes.Buffer
	buf.WriteString("ArrowFunction (")
	buf.WriteString("\n")
	if node.ArrowParameters != nil {
		buf.WriteString(PrefixToString(node.ArrowParameters.String(), "  "))
	}
	if node.ConciseBody != nil {
		buf.WriteString(PrefixToString(node.ConciseBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *ArrowParameters) String() string {
	var buf bytes.Buffer
	buf.WriteString("ArrowParameters (")
	buf.WriteString("\n")
	if node.BindingIdentifier != nil {
		buf.WriteString(PrefixToString(node.BindingIdentifier.String(), "  "))
	}
	if node.CoverParenthesizedExpressionAndArrowParameterList != nil {
		buf.WriteString(PrefixToString(node.CoverParenthesizedExpressionAndArrowParameterList.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *ConciseBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("ConciseBody (")
	buf.WriteString("\n")
	if node.AssignmentExpression != nil {
		buf.WriteString(PrefixToString(node.AssignmentExpression.String(), "  "))
	}
	if node.FunctionBody != nil {
		buf.WriteString(PrefixToString(node.FunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *CoverParenthesizedExpressionAndArrowParameterList) String() string {
	var buf bytes.Buffer
	buf.WriteString("CoverParenthesizedExpressionAndArrowParameterList (")
	buf.WriteString("\n")
	if node.Expression != nil {
		buf.WriteString(PrefixToString(node.Expression.String(), "  "))
	}
	if node.BindingIdentifier != nil {
		buf.WriteString(PrefixToString(node.BindingIdentifier.String(), "  "))
	}
	if node.BindingPattern != nil {
		buf.WriteString(PrefixToString(node.BindingPattern.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Comma", node.Comma), "  "))
	buf.WriteString("\n")
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Ellipsis", node.Ellipsis), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *MethodDefinition) String() string {
	var buf bytes.Buffer
	buf.WriteString("MethodDefinition (")
	buf.WriteString("\n")
	if node.PropertyName != nil {
		buf.WriteString(PrefixToString(node.PropertyName.String(), "  "))
	}
	if node.UniqueFormalPatameters != nil {
		buf.WriteString(PrefixToString(node.UniqueFormalPatameters.String(), "  "))
	}
	if node.FunctionBody != nil {
		buf.WriteString(PrefixToString(node.FunctionBody.String(), "  "))
	}
	if node.GeneratorMethod != nil {
		buf.WriteString(PrefixToString(node.GeneratorMethod.String(), "  "))
	}
	if node.AsyncMethod != nil {
		buf.WriteString(PrefixToString(node.AsyncMethod.String(), "  "))
	}
	if node.AsyncGeneratorMethod != nil {
		buf.WriteString(PrefixToString(node.AsyncGeneratorMethod.String(), "  "))
	}
	if node.PropertySetParameterList != nil {
		buf.WriteString(PrefixToString(node.PropertySetParameterList.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Get", node.Get), "  "))
	buf.WriteString("\n")
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Set", node.Set), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *PropertySetParameterList) String() string {
	var buf bytes.Buffer
	buf.WriteString("PropertySetParameterList (")
	buf.WriteString("\n")
	if node.FormalParameter != nil {
		buf.WriteString(PrefixToString(node.FormalParameter.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *UniqueFormalParameters) String() string {
	var buf bytes.Buffer
	buf.WriteString("UniqueFormalParameters (")
	buf.WriteString("\n")
	if node.FormalParameters != nil {
		buf.WriteString(PrefixToString(node.FormalParameters.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *GeneratorMethod) String() string {
	var buf bytes.Buffer
	buf.WriteString("GeneratorMethod (")
	buf.WriteString("\n")
	if node.PropertyName != nil {
		buf.WriteString(PrefixToString(node.PropertyName.String(), "  "))
	}
	if node.UniqueFormalParameters != nil {
		buf.WriteString(PrefixToString(node.UniqueFormalParameters.String(), "  "))
	}
	if node.GeneratorBody != nil {
		buf.WriteString(PrefixToString(node.GeneratorBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncMethod) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncMethod (")
	buf.WriteString("\n")
	if node.PropertyName != nil {
		buf.WriteString(PrefixToString(node.PropertyName.String(), "  "))
	}
	if node.UniqueFormalParameters != nil {
		buf.WriteString(PrefixToString(node.UniqueFormalParameters.String(), "  "))
	}
	if node.AsyncFunctionBody != nil {
		buf.WriteString(PrefixToString(node.AsyncFunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncFunctionBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncFunctionBody (")
	buf.WriteString("\n")
	if node.FunctionBody != nil {
		buf.WriteString(PrefixToString(node.FunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncGeneratorMethod) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncGeneratorMethod (")
	buf.WriteString("\n")
	if node.PropertyName != nil {
		buf.WriteString(PrefixToString(node.PropertyName.String(), "  "))
	}
	if node.UniqueFormalParameters != nil {
		buf.WriteString(PrefixToString(node.UniqueFormalParameters.String(), "  "))
	}
	if node.AsyncGeneratorBody != nil {
		buf.WriteString(PrefixToString(node.AsyncGeneratorBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncGeneratorBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncGeneratorBody (")
	buf.WriteString("\n")
	if node.FunctionBody != nil {
		buf.WriteString(PrefixToString(node.FunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncArrowFunction) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncArrowFunction (")
	buf.WriteString("\n")
	if node.AsyncArrowBindingIdentifier != nil {
		buf.WriteString(PrefixToString(node.AsyncArrowBindingIdentifier.String(), "  "))
	}
	if node.AsyncConciseBody != nil {
		buf.WriteString(PrefixToString(node.AsyncConciseBody.String(), "  "))
	}
	if node.CoverCallExpressionAndAsyncArrowHead != nil {
		buf.WriteString(PrefixToString(node.CoverCallExpressionAndAsyncArrowHead.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncConciseBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncConciseBody (")
	buf.WriteString("\n")
	if node.AssignmentExpression != nil {
		buf.WriteString(PrefixToString(node.AssignmentExpression.String(), "  "))
	}
	if node.AsyncFunctionBody != nil {
		buf.WriteString(PrefixToString(node.AsyncFunctionBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *AsyncArrowBindingIdentifier) String() string {
	var buf bytes.Buffer
	buf.WriteString("AsyncArrowBindingIdentifier (")
	buf.WriteString("\n")
	if node.BindingIdentifier != nil {
		buf.WriteString(PrefixToString(node.BindingIdentifier.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *CoverCallExpressionAndAsyncArrowHead) String() string {
	var buf bytes.Buffer
	buf.WriteString("CoverCallExpressionAndAsyncArrowHead (")
	buf.WriteString("\n")
	if node.MemberExpression != nil {
		buf.WriteString(PrefixToString(node.MemberExpression.String(), "  "))
	}
	if node.Arguments != nil {
		buf.WriteString(PrefixToString(node.Arguments.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}
