// Code generated by "aststring"; DO NOT EDIT.
package ast

import (
	"bytes"
	"fmt"
)

func (node *Initializer) String() string {
	var buf bytes.Buffer
	buf.WriteString("Initializer (")
	buf.WriteString("\n")
	if node.AssignmentExpression != nil {
		buf.WriteString(PrefixToString(node.AssignmentExpression.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *Elision) String() string {
	var buf bytes.Buffer
	buf.WriteString("Elision (")
	buf.WriteString("\n")
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Commas", node.Commas), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *SuperProperty) String() string {
	var buf bytes.Buffer
	buf.WriteString("SuperProperty (")
	buf.WriteString("\n")
	if node.Expression != nil {
		buf.WriteString(PrefixToString(node.Expression.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "IdentifierName", node.IdentifierName), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *MetaProperty) String() string {
	var buf bytes.Buffer
	buf.WriteString("MetaProperty (")
	buf.WriteString("\n")
	if node.NewTarget != nil {
		buf.WriteString(PrefixToString(node.NewTarget.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *NewTarget) String() string {
	var buf bytes.Buffer
	buf.WriteString("NewTarget (")
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *Arguments) String() string {
	var buf bytes.Buffer
	buf.WriteString("Arguments (")
	buf.WriteString("\n")
	if node.ArgumentList != nil {
		buf.WriteString(PrefixToString(node.ArgumentList.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Comma", node.Comma), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *ArgumentList) String() string {
	var buf bytes.Buffer
	buf.WriteString("ArgumentList (")
	buf.WriteString("\n")
	if node.AssignmentExpression != nil {
		buf.WriteString(PrefixToString(node.AssignmentExpression.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Ellipsis", node.Ellipsis), "  "))
	buf.WriteString("\n")
	if node.ArgumentList != nil {
		buf.WriteString(PrefixToString(node.ArgumentList.String(), "  "))
	}
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Comma", node.Comma), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *LetOrConst) String() string {
	var buf bytes.Buffer
	buf.WriteString("LetOrConst (")
	buf.WriteString("\n")
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Let", node.Let), "  "))
	buf.WriteString("\n")
	buf.WriteString(PrefixToString(fmt.Sprintf("%v: %v", "Const", node.Const), "  "))
	buf.WriteString("\n")
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}
