// Code generated by "aststring"; DO NOT EDIT.
package ast

import "bytes"

func (node *Script) String() string {
	var buf bytes.Buffer
	buf.WriteString("Script (")
	buf.WriteString("\n")
	if node.ScriptBody != nil {
		buf.WriteString(PrefixToString(node.ScriptBody.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}

func (node *ScriptBody) String() string {
	var buf bytes.Buffer
	buf.WriteString("ScriptBody (")
	buf.WriteString("\n")
	if node.StatementList != nil {
		buf.WriteString(PrefixToString(node.StatementList.String(), "  "))
	}
	buf.WriteString(")")
	buf.WriteString("\n")
	return buf.String()
}
